### ISSUE TITLE
Error when including library

### ISSUE THREAD

**Issue by scottwestover** [LivePersonInc/node-agent-sdk#16]
When I try to use the example code provided in the README.md file, I get the following error: 

```
/Users/SWestover/Desktop/electronApp/node-js-getting-started/node_modules/node-agent-sdk/lib/AgentSDK.js:110
            ({body, type, headers} = Transformer[type]({body, type, headers},this));
             ^
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/SWestover/Desktop/electronApp/node-js-getting-started/node_modules/node-agent-sdk/index.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
Here is the code I am using for reference:
```
const Agent = require('node-agent-sdk').Agent;

const agent = new Agent({
    accountId: "5477507",
    username: "TestUserB",
    password: "{Removed}"
});

agent.on('connected', () => {
    console.log(`connected...`);
    agent.subscribeExConversations({
        'convState': ['OPEN']
    }, (err, resp) => {
        console.log('subscribed successfully', err, resp);
    });
});
```

I also tried running the echo example, but I get the same error.

**Comment by cjames1224** [comment]
This is usually due to using an older version of Nodejs. I believe you need at least v6.10.0 LTS (long-term support) or higher.

**Comment by scottwestover** [comment]
@cjames1224 Thanks for the tip. That fixed my issue.
